version: '2'

services:
  finder-cron:
    build: .
    privileged: true
    env_file:
      - .env
    restart: unless-stopped
    init: true
    logging:
      driver: json-file
      options:
        max-size: '512k'
        max-file: '10'
