services:
  finder-cron:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    init: true
    mem_limit: 384m
    mem_swap_limit: 384m
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "10"
    volumes:
      - ./data:/app/data
